table:
  name: application_status_type
  schema: public
is_enum: true
array_relationships:
- name: applications
  using:
    foreign_key_constraint_on:
      column: status
      table:
        name: application
        schema: public
