version: '3.6'
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS512", "key": "1234567890123456789012345678901212345678901234567890123456789012"}'
      HASURA_GRAPHQL_ADMIN_SECRET: password
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
  tunnel:
    image: wernight/ngrok
    network_mode: host
    ports:
      - 4040:4040
    environment:
      NGROK_AUTH: nPM8fBkcpU6FWNLjHuju_YBYXGhivyCuKLMzxVP4B
      NGROK_SUBDOMAIN: gitez
      NGROK_PORT: 8080

volumes:
  db_data:
